name: SSH and Run Script

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add known hosts
      run: ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} 'echo "SSH connection successful"'
        python3 -m venv yolo
        source yolo/bin/activate
        echo "Current directory: $(pwd)"

        cd /home/ubuntu/objectdetection/yolocode || { echo "Directory not found"; exit 1; }
        echo "Changed directory to /home/ubuntu/objectdetection/yolocode"
        
        
        
